// Code generated by go-swagger; DO NOT EDIT.

/*
Package server Harbor API
These APIs provide services for manipulating Harbor project.


    Schemes:
      http
      https
    Host: localhost
    BasePath: /api/v2.0
    Version: 2.0

    Consumes:
    - application/json

    Produces:
    - application/json
    - application/octet-stream
    - text/plain

swagger:meta
*/
package server
