// Code generated by go-swagger; DO NOT EDIT.

package systeminfo

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/goharbor/harbor/src/server/v2.0/models"
)

// GetSysteminfoVolumesOKCode is the HTTP code returned for type GetSysteminfoVolumesOK
const GetSysteminfoVolumesOKCode int = 200

/*GetSysteminfoVolumesOK Get system volumes successfully.

swagger:response getSysteminfoVolumesOK
*/
type GetSysteminfoVolumesOK struct {

	/*
	  In: Body
	*/
	Payload *models.SystemInfo `json:"body,omitempty"`
}

// NewGetSysteminfoVolumesOK creates GetSysteminfoVolumesOK with default headers values
func NewGetSysteminfoVolumesOK() *GetSysteminfoVolumesOK {

	return &GetSysteminfoVolumesOK{}
}

// WithPayload adds the payload to the get systeminfo volumes o k response
func (o *GetSysteminfoVolumesOK) WithPayload(payload *models.SystemInfo) *GetSysteminfoVolumesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get systeminfo volumes o k response
func (o *GetSysteminfoVolumesOK) SetPayload(payload *models.SystemInfo) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSysteminfoVolumesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetSysteminfoVolumesUnauthorizedCode is the HTTP code returned for type GetSysteminfoVolumesUnauthorized
const GetSysteminfoVolumesUnauthorizedCode int = 401

/*GetSysteminfoVolumesUnauthorized Unauthorized

swagger:response getSysteminfoVolumesUnauthorized
*/
type GetSysteminfoVolumesUnauthorized struct {
	/*The ID of the corresponding request for the response

	 */
	XRequestID string `json:"X-Request-Id"`

	/*
	  In: Body
	*/
	Payload *models.Errors `json:"body,omitempty"`
}

// NewGetSysteminfoVolumesUnauthorized creates GetSysteminfoVolumesUnauthorized with default headers values
func NewGetSysteminfoVolumesUnauthorized() *GetSysteminfoVolumesUnauthorized {

	return &GetSysteminfoVolumesUnauthorized{}
}

// WithXRequestID adds the xRequestId to the get systeminfo volumes unauthorized response
func (o *GetSysteminfoVolumesUnauthorized) WithXRequestID(xRequestID string) *GetSysteminfoVolumesUnauthorized {
	o.XRequestID = xRequestID
	return o
}

// SetXRequestID sets the xRequestId to the get systeminfo volumes unauthorized response
func (o *GetSysteminfoVolumesUnauthorized) SetXRequestID(xRequestID string) {
	o.XRequestID = xRequestID
}

// WithPayload adds the payload to the get systeminfo volumes unauthorized response
func (o *GetSysteminfoVolumesUnauthorized) WithPayload(payload *models.Errors) *GetSysteminfoVolumesUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get systeminfo volumes unauthorized response
func (o *GetSysteminfoVolumesUnauthorized) SetPayload(payload *models.Errors) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSysteminfoVolumesUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header X-Request-Id

	xRequestID := o.XRequestID
	if xRequestID != "" {
		rw.Header().Set("X-Request-Id", xRequestID)
	}

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetSysteminfoVolumesForbiddenCode is the HTTP code returned for type GetSysteminfoVolumesForbidden
const GetSysteminfoVolumesForbiddenCode int = 403

/*GetSysteminfoVolumesForbidden Forbidden

swagger:response getSysteminfoVolumesForbidden
*/
type GetSysteminfoVolumesForbidden struct {
	/*The ID of the corresponding request for the response

	 */
	XRequestID string `json:"X-Request-Id"`

	/*
	  In: Body
	*/
	Payload *models.Errors `json:"body,omitempty"`
}

// NewGetSysteminfoVolumesForbidden creates GetSysteminfoVolumesForbidden with default headers values
func NewGetSysteminfoVolumesForbidden() *GetSysteminfoVolumesForbidden {

	return &GetSysteminfoVolumesForbidden{}
}

// WithXRequestID adds the xRequestId to the get systeminfo volumes forbidden response
func (o *GetSysteminfoVolumesForbidden) WithXRequestID(xRequestID string) *GetSysteminfoVolumesForbidden {
	o.XRequestID = xRequestID
	return o
}

// SetXRequestID sets the xRequestId to the get systeminfo volumes forbidden response
func (o *GetSysteminfoVolumesForbidden) SetXRequestID(xRequestID string) {
	o.XRequestID = xRequestID
}

// WithPayload adds the payload to the get systeminfo volumes forbidden response
func (o *GetSysteminfoVolumesForbidden) WithPayload(payload *models.Errors) *GetSysteminfoVolumesForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get systeminfo volumes forbidden response
func (o *GetSysteminfoVolumesForbidden) SetPayload(payload *models.Errors) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSysteminfoVolumesForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header X-Request-Id

	xRequestID := o.XRequestID
	if xRequestID != "" {
		rw.Header().Set("X-Request-Id", xRequestID)
	}

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetSysteminfoVolumesNotFoundCode is the HTTP code returned for type GetSysteminfoVolumesNotFound
const GetSysteminfoVolumesNotFoundCode int = 404

/*GetSysteminfoVolumesNotFound Not found

swagger:response getSysteminfoVolumesNotFound
*/
type GetSysteminfoVolumesNotFound struct {
	/*The ID of the corresponding request for the response

	 */
	XRequestID string `json:"X-Request-Id"`

	/*
	  In: Body
	*/
	Payload *models.Errors `json:"body,omitempty"`
}

// NewGetSysteminfoVolumesNotFound creates GetSysteminfoVolumesNotFound with default headers values
func NewGetSysteminfoVolumesNotFound() *GetSysteminfoVolumesNotFound {

	return &GetSysteminfoVolumesNotFound{}
}

// WithXRequestID adds the xRequestId to the get systeminfo volumes not found response
func (o *GetSysteminfoVolumesNotFound) WithXRequestID(xRequestID string) *GetSysteminfoVolumesNotFound {
	o.XRequestID = xRequestID
	return o
}

// SetXRequestID sets the xRequestId to the get systeminfo volumes not found response
func (o *GetSysteminfoVolumesNotFound) SetXRequestID(xRequestID string) {
	o.XRequestID = xRequestID
}

// WithPayload adds the payload to the get systeminfo volumes not found response
func (o *GetSysteminfoVolumesNotFound) WithPayload(payload *models.Errors) *GetSysteminfoVolumesNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get systeminfo volumes not found response
func (o *GetSysteminfoVolumesNotFound) SetPayload(payload *models.Errors) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSysteminfoVolumesNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header X-Request-Id

	xRequestID := o.XRequestID
	if xRequestID != "" {
		rw.Header().Set("X-Request-Id", xRequestID)
	}

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetSysteminfoVolumesInternalServerErrorCode is the HTTP code returned for type GetSysteminfoVolumesInternalServerError
const GetSysteminfoVolumesInternalServerErrorCode int = 500

/*GetSysteminfoVolumesInternalServerError Internal server error

swagger:response getSysteminfoVolumesInternalServerError
*/
type GetSysteminfoVolumesInternalServerError struct {
	/*The ID of the corresponding request for the response

	 */
	XRequestID string `json:"X-Request-Id"`

	/*
	  In: Body
	*/
	Payload *models.Errors `json:"body,omitempty"`
}

// NewGetSysteminfoVolumesInternalServerError creates GetSysteminfoVolumesInternalServerError with default headers values
func NewGetSysteminfoVolumesInternalServerError() *GetSysteminfoVolumesInternalServerError {

	return &GetSysteminfoVolumesInternalServerError{}
}

// WithXRequestID adds the xRequestId to the get systeminfo volumes internal server error response
func (o *GetSysteminfoVolumesInternalServerError) WithXRequestID(xRequestID string) *GetSysteminfoVolumesInternalServerError {
	o.XRequestID = xRequestID
	return o
}

// SetXRequestID sets the xRequestId to the get systeminfo volumes internal server error response
func (o *GetSysteminfoVolumesInternalServerError) SetXRequestID(xRequestID string) {
	o.XRequestID = xRequestID
}

// WithPayload adds the payload to the get systeminfo volumes internal server error response
func (o *GetSysteminfoVolumesInternalServerError) WithPayload(payload *models.Errors) *GetSysteminfoVolumesInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get systeminfo volumes internal server error response
func (o *GetSysteminfoVolumesInternalServerError) SetPayload(payload *models.Errors) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSysteminfoVolumesInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header X-Request-Id

	xRequestID := o.XRequestID
	if xRequestID != "" {
		rw.Header().Set("X-Request-Id", xRequestID)
	}

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
