// Code generated by go-swagger; DO NOT EDIT.

package systeminfo

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetSysteminfoHandlerFunc turns a function with the right signature into a get systeminfo handler
type GetSysteminfoHandlerFunc func(GetSysteminfoParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetSysteminfoHandlerFunc) Handle(params GetSysteminfoParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetSysteminfoHandler interface for that can handle valid get systeminfo params
type GetSysteminfoHandler interface {
	Handle(GetSysteminfoParams, interface{}) middleware.Responder
}

// NewGetSysteminfo creates a new http.Handler for the get systeminfo operation
func NewGetSysteminfo(ctx *middleware.Context, handler GetSysteminfoHandler) *GetSysteminfo {
	return &GetSysteminfo{Context: ctx, Handler: handler}
}

/*GetSysteminfo swagger:route GET /systeminfo systeminfo getSysteminfo

Get general system info

This API is for retrieving general system info, this can be called by anonymous request.  Some attributes will be omitted in the response when this API is called by anonymous request.


*/
type GetSysteminfo struct {
	Context *middleware.Context
	Handler GetSysteminfoHandler
}

func (o *GetSysteminfo) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetSysteminfoParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
