// Code generated by go-swagger; DO NOT EDIT.

package systeminfo

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetSysteminfoVolumesHandlerFunc turns a function with the right signature into a get systeminfo volumes handler
type GetSysteminfoVolumesHandlerFunc func(GetSysteminfoVolumesParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetSysteminfoVolumesHandlerFunc) Handle(params GetSysteminfoVolumesParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetSysteminfoVolumesHandler interface for that can handle valid get systeminfo volumes params
type GetSysteminfoVolumesHandler interface {
	Handle(GetSysteminfoVolumesParams, interface{}) middleware.Responder
}

// NewGetSysteminfoVolumes creates a new http.Handler for the get systeminfo volumes operation
func NewGetSysteminfoVolumes(ctx *middleware.Context, handler GetSysteminfoVolumesHandler) *GetSysteminfoVolumes {
	return &GetSysteminfoVolumes{Context: ctx, Handler: handler}
}

/*GetSysteminfoVolumes swagger:route GET /systeminfo/volumes systeminfo getSysteminfoVolumes

Get system volume info (total/free size).

This endpoint is for retrieving system volume info that only provides for admin user.  Note that the response only reflects the storage status of local disk.


*/
type GetSysteminfoVolumes struct {
	Context *middleware.Context
	Handler GetSysteminfoVolumesHandler
}

func (o *GetSysteminfoVolumes) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetSysteminfoVolumesParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
