// Code generated by go-swagger; DO NOT EDIT.

package replication

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"github.com/goharbor/harbor/src/server/v2.0/models"
)

// NewStartReplicationParams creates a new StartReplicationParams object
// no default values defined in spec.
func NewStartReplicationParams() StartReplicationParams {

	return StartReplicationParams{}
}

// StartReplicationParams contains all the bound params for the start replication operation
// typically these are obtained from a http.Request
//
// swagger:parameters startReplication
type StartReplicationParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The ID of policy that the execution belongs to
	  Required: true
	  In: body
	*/
	Execution *models.StartReplicationExecution
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewStartReplicationParams() beforehand.
func (o *StartReplicationParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.StartReplicationExecution
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("execution", "body"))
			} else {
				res = append(res, errors.NewParseError("execution", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Execution = &body
			}
		}
	} else {
		res = append(res, errors.Required("execution", "body"))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
