// Code generated by go-swagger; DO NOT EDIT.

package gc

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetGCParams creates a new GetGCParams object
// no default values defined in spec.
func NewGetGCParams() GetGCParams {

	return GetGCParams{}
}

// GetGCParams contains all the bound params for the get GC operation
// typically these are obtained from a http.Request
//
// swagger:parameters getGC
type GetGCParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The ID of the gc log
	  Required: true
	  In: path
	*/
	GCID int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetGCParams() beforehand.
func (o *GetGCParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rGCID, rhkGCID, _ := route.Params.GetOK("gc_id")
	if err := o.bindGCID(rGCID, rhkGCID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindGCID binds and validates parameter GCID from path.
func (o *GetGCParams) bindGCID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("gc_id", "path", "int64", raw)
	}
	o.GCID = value

	return nil
}
