// Code generated by go-swagger; DO NOT EDIT.

package retention

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"github.com/goharbor/harbor/src/server/v2.0/models"
)

// NewCreateRetentionParams creates a new CreateRetentionParams object
// no default values defined in spec.
func NewCreateRetentionParams() CreateRetentionParams {

	return CreateRetentionParams{}
}

// CreateRetentionParams contains all the bound params for the create retention operation
// typically these are obtained from a http.Request
//
// swagger:parameters createRetention
type CreateRetentionParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Create Retention Policy successfully.
	  Required: true
	  In: body
	*/
	Policy *models.RetentionPolicy
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewCreateRetentionParams() beforehand.
func (o *CreateRetentionParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.RetentionPolicy
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("policy", "body"))
			} else {
				res = append(res, errors.NewParseError("policy", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Policy = &body
			}
		}
	} else {
		res = append(res, errors.Required("policy", "body"))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
